
export const CATEGORIES = [
  'Arts & Crafts',
  'Beauty & Salon',
  'Education',
  'Fashion & Clothing',
  'Food & Grocery',
  'Health & Wellness',
  'Professional Services',
  'Real Estate',
  'Restaurant',
  'Retail',
  'Technology',
  'Transportation',
];

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'France',
  'Germany',
  'Netherlands',
  'Belgium',
  'Italy',
  'Spain',
  'Australia',
];

export const mockUser = {
  id: '1',
  name: 'Mobisa Frankline',
  email: 'amara@example.com',
  role: 'premium',
  country_of_residence: 'United Kingdom',
  profile_image: 'https://images.unsplash.com/photo-1687422809654-579d81c29d32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-10-20T14:30:00Z',
};

export const mockListings = [
  {
    id: '1',
    owner_id: '1',
    owner_name: 'Jimmy John',
    title: 'Jimmy John Beauty Salon & Supplies',
    description: 'Your best hair day is waiting! We offer professional hair services including braiding, barbering, and styling with premium care and attention.',
    category: ['Beauty & Salon', 'Haircare'],
    address: '3313 Naaman School Rd Suite 400',
    country: 'United States',
    city: 'Garland, TX',
    phone: '+1 214-515-2495',
    email: null,
    website: null,
    social_links: {},
    images: [
      'https://africanyellowpagesusa.com/wp-content/uploads/2025/10/Hair.jpg'
    ],
    is_premium: true,
    status: 'active',
    featured_priority: 1,
    views_count: 2430,
    rating: 4.8,
    verified: true,
    created_at: '2024-03-05T11:00:00Z',
    updated_at: '2024-10-24T10:00:00Z'
  },
  {
    id: '2',
    owner_id: '2',
    owner_name: 'Infinite Care Mobility LLC',
    title: 'Infinite Care Mobility',
    description: 'Your trusted partner in non-emergency transportation for seniors and the disabled in North Texas. We provide safe, reliable, and compassionate mobility solutions.',
    category: ['Transportation', 'Healthcare Services'],
    address: null,
    country: 'United States',
    city: 'North Texas',
    phone: '+1 469-400-0264',
    email: null,
    website: 'https://www.infinitecaremobility.com',
    social_links: {},
    images: [
      'https://africanyellowpagesusa.com/wp-content/uploads/2025/06/FO826CEBAEFC4_-1536x1258.jpg'
    ],
    is_premium: true,
    status: 'active',
    featured_priority: 2,
    views_count: 1985,
    rating: 4.9,
    verified: true,
    created_at: '2024-03-10T11:00:00Z',
    updated_at: '2024-10-24T10:00:00Z'
  },
  {
    id: '3',
    owner_id: '3',
    owner_name: 'Chetrading Financial Group',
    title: 'Chetrading Tax Services',
    description: 'Comprehensive tax preparation services for individuals and businesses, including tax returns, credit repair, accounting, and financial consulting.',
    category: ['Financial Services', 'Tax & Accounting'],
    address: '3939 South Polk St, Suite 210',
    country: 'United States',
    city: 'Dallas, TX',
    phone: '+1 469-970-6160',
    email: 'info@chetrading.com',
    website: 'https://www.chetrading.com',
    social_links: {},
    images: [
      'https://africanyellowpagesusa.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-11-05-at-23.37.00_f94a269e.jpg'
    ],
    is_premium: true,
    status: 'active',
    featured_priority: 3,
    views_count: 1754,
    rating: 4.7,
    verified: true,
    created_at: '2024-04-01T11:00:00Z',
    updated_at: '2024-10-24T10:00:00Z'
  },
  {
    "id": "4",
    "owner_id": "4",
    "owner_name": "JEMPRO Roofing & Restoration",
    "title": "JEMPRO Roofing & Restoration Services",
    "description": "Professional roofing replacement and comprehensive home restoration services including home renovation, windows & doors, painting, flooring, gutter installation, patios, fencing, and handyman services.",
    "category": ["Home Services", "Construction", "Roofing"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "+1 469-554-2020",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/jempro-roofing-services.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 892,
    "rating": 4.5,
    "verified": true,
    "created_at": "2024-03-15T09:00:00Z",
    "updated_at": "2024-10-24T09:00:00Z"
  },
  {
    "id": "5",
    "owner_id": "5",
    "owner_name": "Adeyemi Law Firm",
    "title": "Adeyemi Law Firm - Personal Injury Attorney",
    "description": "Personal injury law firm specializing in trucking accident cases. Providing legal assistance and representation for injured individuals, truck drivers, and dispatchers.",
    "category": ["Legal Services", "Personal Injury", "Trucking Accidents"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/adeyemi-law-firm.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 1245,
    "rating": 4.8,
    "verified": true,
    "created_at": "2024-02-20T10:00:00Z",
    "updated_at": "2024-10-24T09:30:00Z"
  },
  {
    "id": "6",
    "owner_id": "6",
    "owner_name": "Cates Kitchen Services",
    "title": "Cates Kitchen Services",
    "description": "Professional catering service offering delicious and tasty meals for all occasions. Specializing in both small family dinners and large corporate functions including weddings, office lunches, Christmas events, birthdays, and graduations. Offers diverse menu with experienced chefs and special diet options.",
    "category": ["Food & Catering", "Restaurant Services", "Event Catering"],
    "address": "",
    "country": "United States",
    "city": "Rowlett, TX",
    "phone": "+1 218-940-0035",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/cates-kitchen-services.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1567,
    "rating": 4.6,
    "verified": true,
    "created_at": "2024-01-10T08:00:00Z",
    "updated_at": "2024-10-24T11:00:00Z"
  },
  {
    "id": "7",
    "owner_id": "7",
    "owner_name": "Dynasty Tax Services",
    "title": "Mastering Tax Consultation",
    "description": "Professional tax consultancy training and mentorship program helping entrepreneurs build profitable ventures from scratch to six figures in less than 12 months. Offers expert guidance, community connection, personalized mentorship and webinar sessions.",
    "category": ["Financial Services", "Education & Training", "Tax Consultation"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "",
    "email": "",
    "website": "https://go.dynastytakservices.com",
    "social_links": {},
    "images": [
      "https://example.com/dynasty-tax-services.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 2100,
    "rating": 4.8,
    "verified": true,
    "created_at": "2024-05-01T10:00:00Z",
    "updated_at": "2024-10-24T18:32:15Z"
  },
  {
    "id": "8",
    "owner_id": "8",
    "owner_name": "Salam & Associates",
    "title": "Salam & Associates - Attorneys and Counselors",
    "description": "Personal injury law firm providing legal representation for accident victims. Specializing in helping clients shoulder their burdens during difficult times with compassionate legal counsel.",
    "category": ["Legal Services", "Personal Injury"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "+1 972-437-1900",
    "email": "",
    "website": "https://www.dfwpersonalinjurylawyers.com",
    "social_links": {},
    "images": [
      "https://example.com/salam-associates.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1560,
    "rating": 4.6,
    "verified": true,
    "created_at": "2024-03-20T09:00:00Z",
    "updated_at": "2024-10-24T18:32:15Z"
  },
  {
    "id": "9",
    "owner_id": "9",
    "owner_name": "Trust n LLC - Susan Young & James Fornett",
    "title": "Trust n LLC - Estate Planning & Asset Protection",
    "description": "Comprehensive estate planning and asset protection services including living trusts, business formation, and legacy planning. Helping clients secure their assets and safeguard their legacy.",
    "category": ["Legal Services", "Financial Planning", "Estate Planning"],
    "address": "3010 Lyndon B Johnson Fwy #1200",
    "country": "United States",
    "city": "Dallas, TX 75234",
    "phone": "+1 412-225-3282",
    "email": "info@trustnllc.com",
    "website": "https://www.trustnllc.com",
    "social_links": {},
    "images": [
      "https://example.com/trust-n-llc.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 3,
    "views_count": 1890,
    "rating": 4.9,
    "verified": true,
    "created_at": "2024-02-15T08:00:00Z",
    "updated_at": "2024-10-24T18:32:15Z"
  },
  {
    "id": "10",
    "owner_id": "10",
    "owner_name": "Divine Foot Care Center",
    "title": "Divine Foot Care Center - Podiatry Services",
    "description": "Professional foot care and podiatry services offering 10% discount for every office visit. Specialized in keeping Texas on their feet with comprehensive foot health solutions.",
    "category": ["Healthcare", "Podiatry", "Medical Services"],
    "address": "2000 Esters Rd. #104",
    "country": "United States",
    "city": "Irving, TX 75061",
    "phone": "+1 972-790-2800",
    "email": "",
    "website": "https://www.divinefootcarecenter.com",
    "social_links": {},
    "images": [
      "https://example.com/divine-foot-care.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1340,
    "rating": 4.7,
    "verified": true,
    "created_at": "2024-04-10T11:00:00Z",
    "updated_at": "2024-10-24T18:32:15Z"
  },
  {
    "id": "11",
    "owner_id": "11",
    "owner_name": "Ikoni African Market",
    "title": "Ikoni African Market - Sausages & Groceries",
    "description": "African market specializing in sausages and various African food products. Providing authentic African groceries and food items to the community.",
    "category": ["Retail", "Food & Groceries", "African Market"],
    "address": "1100 Clinton Avenue",
    "country": "United States",
    "city": "Irvington, NJ 07111",
    "phone": "+1 856-422-9049",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/ikoni-african-market.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 980,
    "rating": 4.3,
    "verified": false,
    "created_at": "2024-05-15T12:00:00Z",
    "updated_at": "2024-10-24T18:32:16Z"
  },
  {
    "id": "12",
    "owner_id": "12",
    "owner_name": "Best Product Electronics",
    "title": "Best Product - Fire TV Stick & Entertainment",
    "description": "Electronics retailer specializing in Fire TV Stick 4K with unlimited movies, TV shows, premium channels, sporting events, and adult content. Includes free VPN and worldwide shipping.",
    "category": ["Electronics", "Retail", "Entertainment"],
    "address": "3005 Parker Road",
    "country": "United States",
    "city": "Anna, TX 75409",
    "phone": "+1 214-429-7011",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/best-product-electronics.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 2450,
    "rating": 4.2,
    "verified": false,
    "created_at": "2024-03-05T13:00:00Z",
    "updated_at": "2024-10-24T18:32:16Z"
  },
  {
    "id": "13",
    "owner_id": "13",
    "owner_name": "National Association of Hebrews",
    "title": "Hebrew Federal Credit Union - HFCU",
    "description": "Financial services offering individual and business checking accounts, savings accounts, personal loans, car loans, SBA loans and other business loans through the Hebrew Federal Credit Union.",
    "category": ["Financial Services", "Banking", "Credit Union"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "",
    "email": "",
    "website": "https://www.naheb.net",
    "social_links": {},
    "images": [
      "https://example.com/hebrew-credit-union.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 1670,
    "rating": 4.5,
    "verified": true,
    "created_at": "2024-01-20T14:00:00Z",
    "updated_at": "2024-10-24T18:32:16Z"
  },
  {
    "id": "14",
    "owner_id": "14",
    "owner_name": "Althea Furniture",
    "title": "Althea Furniture - Home Furnishings",
    "description": "Furniture store offering stylish and comfortable furniture and home accessories. Providing quality furniture solutions with simple style and livable comfort.",
    "category": ["Retail", "Furniture", "Home Decor"],
    "address": "305 Spring Creek Village",
    "country": "United States",
    "city": "Dallas, TX 75248",
    "phone": "+1 972-607-6220",
    "email": "",
    "website": "https://www.altheafurniture.com",
    "social_links": {},
    "images": [
      "https://example.com/althea-furniture.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1980,
    "rating": 4.6,
    "verified": true,
    "created_at": "2024-02-28T15:00:00Z",
    "updated_at": "2024-10-24T18:32:17Z"
  },
  {
    "id": "15",
    "owner_id": "15",
    "owner_name": "African Essence Hairstyles",
    "title": "African Essence Hairstyles - Hair Braiding Salon",
    "description": "Professional hair braiding salon specializing in braiding, crochet, dreadlocks, and weaving services. Open Monday to Saturday with Sunday appointments available.",
    "category": ["Beauty & Personal Care", "Hair Salon", "Braiding Services"],
    "address": "11490 Audelia Rd",
    "country": "United States",
    "city": "Dallas, TX 75243",
    "phone": "+1 972-504-5160",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/african-essence-hairstyles.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1760,
    "rating": 4.4,
    "verified": true,
    "created_at": "2024-04-05T16:00:00Z",
    "updated_at": "2024-10-24T18:32:18Z"
  },
  {
    "id": "16",
    "owner_id": "16",
    "owner_name": "AM's Farm",
    "title": "AM's Farm - Meat Processing",
    "description": "Farm-to-table meat processing service that processes your meat as you wait. Accepts credit cards, food stamps, Zelle and CashApp for convenient payment options.",
    "category": ["Food & Agriculture", "Meat Processing", "Farm Services"],
    "address": "4024 TX-78 W",
    "country": "United States",
    "city": "Wylie, TX 75098",
    "phone": "+1 972-365-7630",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/ams-farm.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1420,
    "rating": 4.5,
    "verified": true,
    "created_at": "2024-03-12T17:00:00Z",
    "updated_at": "2024-10-24T18:32:18Z"
  },
  {
    "id": "17",
    "owner_id": "17",
    "owner_name": "Integrity Insurance Benefits",
    "title": "Integrity Insurance Benefits - Insurance Agency",
    "description": "Comprehensive insurance agency offering life & health insurance, truck insurance, dental, vision, legal plans and various other insurance products. Your trusted one-stop insurance solution.",
    "category": ["Insurance", "Financial Services"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "+1 205-821-8601",
    "email": "",
    "website": "https://www.integrityinsurancebenefits.com",
    "social_links": {},
    "images": [
      "https://example.com/integrity-insurance.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 1890,
    "rating": 4.7,
    "verified": true,
    "created_at": "2024-02-10T18:00:00Z",
    "updated_at": "2024-10-24T18:32:18Z"
  },
  {
    "id": "18",
    "owner_id": "18",
    "owner_name": "TopCare Clinic",
    "title": "TopCare Clinic - Family & Wellness Clinic",
    "description": "Family and wellness clinic providing COVID-19 travel certificates, same-day PCR COVID tests, and PCR combo tests. Offering comprehensive healthcare services with flexible hours.",
    "category": ["Healthcare", "Medical Services", "COVID Testing"],
    "address": "2940 Broadway Blvd, suite 15",
    "country": "United States",
    "city": "Garland, TX 75002",
    "phone": "+1 972-212-4586",
    "email": "",
    "website": "https://www.topcarefamilyclinic.com",
    "social_links": {},
    "images": [
      "https://example.com/topcare-clinic.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 2230,
    "rating": 4.6,
    "verified": true,
    "created_at": "2024-01-25T19:00:00Z",
    "updated_at": "2024-10-24T18:32:19Z"
  },
  {
    "id": "19",
    "owner_id": "19",
    "owner_name": "Roundtrip Safaris",
    "title": "Roundtrip Safaris - Travel & Adventure",
    "description": "Travel agency specializing in safari adventures and vacation packages. All packages include return flights, airport transfers, accommodation, travel insurance, and national park tours.",
    "category": ["Travel & Tourism", "Adventure Tours", "Safari Packages"],
    "address": "555 Republic Dr suite 235",
    "country": "United States",
    "city": "Plano, TX 75074",
    "phone": "+1 202-883-9907",
    "email": "info@roundtripsafaris.com",
    "website": "https://www.roundtripsafaris.com",
    "social_links": {},
    "images": [
      "https://example.com/roundtrip-safaris.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 2560,
    "rating": 4.8,
    "verified": true,
    "created_at": "2024-03-08T20:00:00Z",
    "updated_at": "2024-10-24T18:32:19Z"
  },
  {
    "id": "20",
    "owner_id": "20",
    "owner_name": "Sarah W. Brooks Law Firm",
    "title": "Sarah W. Brooks Law Firm - Legal Services",
    "description": "Law firm practicing family law, immigration law, business law, and personal injury law. Providing comprehensive legal services with experienced attorney representation.",
    "category": ["Legal Services", "Family Law", "Immigration Law"],
    "address": "660 North Central Expressway Ste 102",
    "country": "United States",
    "city": "Plano, TX 75074",
    "phone": "+1 214-888-6834",
    "email": "sarah@sarahbrookslawfirm.com",
    "website": "https://www.sarahbrookslawfirm.com",
    "social_links": {},
    "images": [
      "https://example.com/sarah-brooks-law.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 1780,
    "rating": 4.7,
    "verified": true,
    "created_at": "2024-02-22T21:00:00Z",
    "updated_at": "2024-10-24T18:32:19Z"
  },
  {
    "id": "21",
    "owner_id": "21",
    "owner_name": "Nsutebu Realty",
    "title": "Nsutebu Realty - Real Estate Services",
    "description": "Real estate agency serving the entire DFW area and beyond. Specializing in hassle-free home buying and selling with quick pre-qualification services.",
    "category": ["Real Estate", "Property Services"],
    "address": "",
    "country": "United States",
    "city": "DFW Area",
    "phone": "+1 202-820-3535",
    "email": "",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/nsutebu-realty.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1920,
    "rating": 4.5,
    "verified": true,
    "created_at": "2024-04-18T22:00:00Z",
    "updated_at": "2024-10-24T18:32:19Z"
  },
  {
    "id": "22",
    "owner_id": "22",
    "owner_name": "Sifa Organic Farm",
    "title": "Sifa Organic Farm - Halal Meat Delivery",
    "description": "Organic farm providing fresh, halal meat from goats, sheep, cows, and chickens. Offers custom processing and free delivery for orders over $350 in DFW area.",
    "category": ["Food & Agriculture", "Meat Delivery", "Halal Products"],
    "address": "1967 County Road 1112",
    "country": "United States",
    "city": "Farmersville, TX 75442",
    "phone": "+1 469-558-8839",
    "email": "sifaorganicfarm@gmail.com",
    "website": "https://www.sifafarm.com",
    "social_links": {},
    "images": [
      "https://example.com/sifa-organic-farm.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1650,
    "rating": 4.6,
    "verified": true,
    "created_at": "2024-03-30T23:00:00Z",
    "updated_at": "2024-10-24T18:32:19Z"
  },
  {
    "id": "23",
    "owner_id": "23",
    "owner_name": "Pivot Roofing & Solar",
    "title": "Pivot Roofing & Solar - Roofing & Solar Solutions",
    "description": "Comprehensive roofing and solar services including insurance claim assistance, roof repair & installation, gutters, fence repair, window services, and solar power system design.",
    "category": ["Home Services", "Construction", "Solar Energy"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "+1 214-727-8613",
    "email": "pivotsolar.roofing@gmail.com",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/pivot-roofing-solar.jpg"
    ],
    "is_premium": true,
    "status": "active",
    "featured_priority": 2,
    "views_count": 2340,
    "rating": 4.7,
    "verified": true,
    "created_at": "2024-02-14T08:30:00Z",
    "updated_at": "2024-10-24T18:32:20Z"
  },
  {
    "id": "24",
    "owner_id": "24",
    "owner_name": "Kinjo Taxes",
    "title": "Kinjo Taxes - Tax Preparation Services",
    "description": "Professional tax services including business & individual tax filing, payroll, bookkeeping, business registration, tax ID application, and loan signing notary services. Available year-round.",
    "category": ["Financial Services", "Tax Preparation", "Accounting"],
    "address": "",
    "country": "United States",
    "city": "",
    "phone": "+1 205-447-0395",
    "email": "kinjotaxes@yahoo.com",
    "website": "",
    "social_links": {},
    "images": [
      "https://example.com/kinjo-taxes.jpg"
    ],
    "is_premium": false,
    "status": "active",
    "featured_priority": 1,
    "views_count": 1870,
    "rating": 4.8,
    "verified": true,
    "created_at": "2024-01-30T09:30:00Z",
    "updated_at": "2024-10-24T18:32:20Z"
  }
];

export const mockEvents = [

  {
    id: 'e1',
    listing_id: '1',
    listing_title: 'The Abaluhya Association of Texas',
    title: 'Thanksgiving Dinner Party',
    description: 'Join The Abaluhya Association of Texas for a special Thanksgiving celebration with dinner, community gathering, and cultural festivities.',
    start_datetime: '2025-11-22T17:00:00Z',
    end_datetime: '2025-11-22T22:00:00Z',
    location: 'DEW Event Center, 2435 Steromons Fwy Suite 2418, Lewisville, TX 75067 - Vista Ridge Mall, Entrance #2 next to Dillard\'s',
    banner_image: '../assets/photos/events/abaluhya-thanksgiving.jpg',
    created_at: '2024-10-15T10:00:00Z',
    ticket_price: 'Adults: $75 | Kids under 10yrs: $30',
    contact_info: 'Lonicah Namaswa - Zelle: 7015163159',
    dress_code: 'Black/White/Orange'
  },
  {
    id: 'e2',
    listing_id: '2',
    listing_title: 'African Yellow Pages USA',
    title: 'Business Networking - Achieving Financial Freedom',
    description: 'A FREE community networking forum focused on achieving financial freedom. Connect with professionals and learn strategies for financial success.',
    start_datetime: '2025-11-21T18:00:00Z',
    end_datetime: '2025-11-21T21:00:00Z',
    location: 'Murphys Mansion, 10051 Whitehurst Dr, Dallas, TX 75243',
    banner_image: '../assets/photos/events/financial-freedom-forum.jpg',
    created_at: '2024-10-18T14:30:00Z',
    ticket_price: 'Free Entry | Dinner Plate: $25',
    contact_info: 'RSVP: 469-570-1370 or 612-968-6584',
    theme: 'Achieving Financial Freedom',
    organizers: 'African Yellow Pages USA / Cate\'s Kitchen Services'
  },
  {
    id: 'e3',
    listing_id: '3',
    listing_title: 'African Yellow Pages USA',
    title: 'Business Networking Mixer - Insurance and Financial Freedom',
    description: 'Connect with new clients, form partnerships, learn new marketing techniques, and introduce your products and services.',
    start_datetime: '2025-11-21T18:00:00Z',
    end_datetime: '2025-11-21T21:00:00Z',
    location: 'Murphys Mansion, 10051 Whitehurst Dr, Dallas, TX 75243',
    banner_image: '../assets/photos/events/business-networking-mixer.jpg',
    created_at: '2024-10-20T09:00:00Z',
    ticket_price: 'Free Entry | Dinner: $25',
    contact_info: 'RSVP: Text/Call: 469-570-1370 or 612-968-6584',
    theme: 'Insurance and Financial Freedom'
  }
];

export const mockBlogs = [
  {
    id: 'b1',
    listing_id: '1',
    listing_title: 'Afro Fusion Restaurant',
    author_name: 'Amara Johnson',
    title: '5 Must-Try West African Dishes',
    content: '<p>West African cuisine is incredibly diverse and flavorful. Here are five dishes you absolutely must try...</p>',
    excerpt: 'Discover the rich flavors and cultural heritage behind these authentic West African dishes.',
    banner_image: 'https://images.unsplash.com/photo-1689155494424-d2337856fe3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    tags: ['Food', 'Culture', 'West Africa', 'Recipes'],
    published_at: '2024-10-20T09:00:00Z',
  },
  {
    id: 'b2',
    listing_id: '2',
    listing_title: 'African Roots Fashion Boutique',
    author_name: 'Kwame Asante',
    title: 'The Resurgence of African Print Fashion',
    content: '<p>African print fabrics are taking the global fashion world by storm. Learn about the history and modern interpretations...</p>',
    excerpt: 'How traditional African textiles are influencing contemporary fashion worldwide.',
    banner_image: 'https://images.unsplash.com/photo-1629299342303-3f3622666c41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    tags: ['Fashion', 'Culture', 'African Print', 'Style'],
    published_at: '2024-10-18T12:00:00Z',
  },
  {
    id: 'b3',
    listing_id: '3',
    listing_title: 'Zara\'s Beauty Lounge',
    author_name: 'Zara Okafor',
    title: 'Natural Hair Care Tips for Winter',
    content: '<p>As temperatures drop, natural hair requires special care. Here are my top tips for keeping your hair healthy and moisturized...</p>',
    excerpt: 'Essential winter hair care routine for natural and protective styles.',
    banner_image: 'https://images.unsplash.com/photo-1713845784497-fe3d7ed176d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    tags: ['Beauty', 'Hair Care', 'Natural Hair', 'Winter Tips'],
    published_at: '2024-10-22T15:30:00Z',
  },
];

// API Sample Payloads
export const API_SAMPLES = {
  // POST /listings - Create Listing
  createListing: {
    request: {
      title: 'My African Business',
      description: 'A comprehensive description of the business',
      category: ['Restaurant', 'Food & Grocery'],
      address: '123 Main Street',
      country: 'United Kingdom',
      city: 'London',
      phone: '+44 20 1234 5678',
      email: 'info@mybusiness.com',
      website: 'https://mybusiness.com',
      social_links: {
        facebook: 'mybusiness',
        instagram: 'mybusinessuk',
      },
      is_premium: true,
    },
    response: {
      success: true,
      listing: {
        id: '123',
        status: 'pending',
        // ... full listing object
      },
      payment_required: true,
      checkout_url: 'https://checkout.stripe.com/pay/cs_test_...',
    },
  },

  // GET /listings?q=restaurant&country=UK&premium=true
  searchListings: {
    request: {
      q: 'restaurant',
      category: ['Restaurant'],
      country: 'United Kingdom',
      premium: true,
      page: 1,
      perPage: 20,
    },
    response: {
      listings: mockListings.filter(l => l.is_premium),
      total: 3,
      page: 1,
      perPage: 20,
      totalPages: 1,
    },
  },

  // POST /payments/checkout
  createCheckout: {
    request: {
      plan: 'premium',
      listing_id: '123',
      billing_period: 'monthly',
    },
    response: {
      success: true,
      checkout_url: 'https://checkout.stripe.com/pay/cs_test_a1b2c3...',
      session_id: 'cs_test_a1b2c3d4e5f6g7h8i9j0',
    },
  },

  // POST /admin/approve-listing/:id
  approveListing: {
    request: {
      listing_id: '123',
      status: 'active',
    },
    response: {
      success: true,
      listing: {
        id: '123',
        status: 'active',
        // ... updated listing
      },
    },
  },
};
