// Mock Data for DiasporaBiz

import { BusinessListing, Event, BlogPost, User, Analytics } from './types';

export const CATEGORIES = [
  'Arts & Crafts',
  'Beauty & Salon',
  'Education',
  'Fashion & Clothing',
  'Food & Grocery',
  'Health & Wellness',
  'Professional Services',
  'Real Estate',
  'Restaurant',
  'Retail',
  'Technology',
  'Transportation',
];

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'France',
  'Germany',
  'Netherlands',
  'Belgium',
  'Italy',
  'Spain',
  'Australia',
];

export const mockUser: User = {
  id: '1',
  name: 'Mobisa Frankline',
  email: 'amara@example.com',
  role: 'premium',
  country_of_residence: 'United Kingdom',
  profile_image: 'https://images.unsplash.com/photo-1687422809654-579d81c29d32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-10-20T14:30:00Z',
};

export const mockListings: BusinessListing[] = [
  {
    id: '1',
    owner_id: '1',
    owner_name: 'Amara Johnson',
    title: 'Afro Fusion Restaurant',
    description: 'Authentic African cuisine with a modern twist. Experience the rich flavors of West African dishes prepared by award-winning chefs. We offer catering services for events and parties.',
    category: ['Restaurant', 'Food & Grocery'],
    address: '123 High Street, Camden',
    country: 'United Kingdom',
    city: 'London',
    phone: '+44 20 1234 5678',
    email: 'info@afrofusion.co.uk',
    website: 'https://afrofusion.co.uk',
    social_links: {
      facebook: 'afrofusion',
      instagram: 'afrofusionlondon',
    },
    images: [
      'https://images.unsplash.com/photo-1689155494424-d2337856fe3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
      'https://images.unsplash.com/photo-1655682614757-a9a33fa45c93?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    ],
    is_premium: true,
    status: 'active',
    featured_priority: 1,
    views_count: 2456,
    rating: 4.8,
    verified: true,
    created_at: '2024-02-10T09:00:00Z',
    updated_at: '2024-10-25T12:00:00Z',
  },
  {
    id: '2',
    owner_id: '2',
    owner_name: 'Kwame Asante',
    title: 'African Roots Fashion Boutique',
    description: 'Premium African fashion, fabrics, and accessories. We specialize in custom-made traditional and contemporary African wear for all occasions.',
    category: ['Fashion & Clothing', 'Retail'],
    address: '45 Market Lane',
    country: 'United States',
    city: 'New York',
    phone: '+1 212 555 0123',
    email: 'contact@africanroots.com',
    website: 'https://africanroots.com',
    social_links: {
      instagram: 'africanrootsfashion',
      facebook: 'africanrootsboutique',
    },
    images: [
      'https://images.unsplash.com/photo-1629299342303-3f3622666c41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    ],
    is_premium: true,
    status: 'active',
    featured_priority: 2,
    views_count: 1892,
    rating: 4.9,
    verified: true,
    created_at: '2024-03-05T11:00:00Z',
    updated_at: '2024-10-24T10:00:00Z',
  },
  {
    id: '3',
    owner_id: '3',
    owner_name: 'Zara Okafor',
    title: 'Zara\'s Beauty Lounge',
    description: 'Specialized in natural hair care, braiding, and African beauty treatments. Book your appointment online.',
    category: ['Beauty & Salon', 'Health & Wellness'],
    address: '89 King Street',
    country: 'Canada',
    city: 'Toronto',
    phone: '+1 416 555 7890',
    email: 'hello@zarasbeauty.ca',
    images: [
      'https://images.unsplash.com/photo-1713845784497-fe3d7ed176d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    ],
    is_premium: true,
    status: 'active',
    featured_priority: 3,
    views_count: 1654,
    rating: 4.7,
    verified: true,
    created_at: '2024-04-12T08:30:00Z',
    updated_at: '2024-10-23T16:20:00Z',
  },
  {
    id: '4',
    owner_id: '4',
    owner_name: 'Ibrahim Diallo',
    title: 'African Market & Grocery',
    description: 'Your one-stop shop for African groceries, spices, and specialty items. Fresh produce delivered weekly.',
    category: ['Food & Grocery', 'Retail'],
    address: '234 Commerce Road',
    country: 'France',
    city: 'Paris',
    phone: '+33 1 23 45 67 89',
    email: 'contact@africanmarket.fr',
    images: [
      'https://images.unsplash.com/photo-1655682614757-a9a33fa45c93?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    ],
    is_premium: false,
    status: 'active',
    views_count: 892,
    rating: 4.5,
    verified: false,
    created_at: '2024-06-20T14:00:00Z',
    updated_at: '2024-10-22T09:15:00Z',
  },
  {
    id: '5',
    owner_id: '5',
    owner_name: 'Nia Thompson',
    title: 'Diaspora Tech Solutions',
    description: 'IT consulting and software development services for small businesses. Specializing in e-commerce solutions.',
    category: ['Technology', 'Professional Services'],
    address: '567 Tech Park',
    country: 'United Kingdom',
    city: 'Manchester',
    phone: '+44 161 234 5678',
    email: 'info@diasporatech.uk',
    website: 'https://diasporatech.uk',
    images: [],
    is_premium: false,
    status: 'active',
    views_count: 543,
    rating: 4.6,
    verified: true,
    created_at: '2024-08-10T10:30:00Z',
    updated_at: '2024-10-21T11:45:00Z',
  },
  {
    id: '6',
    owner_id: '6',
    owner_name: 'Kofi Mensah',
    title: 'African Art Gallery',
    description: 'Contemporary and traditional African art. Featuring works from emerging and established African artists across the continent.',
    category: ['Arts & Crafts', 'Retail'],
    address: '78 Gallery Row',
    country: 'United States',
    city: 'Los Angeles',
    phone: '+1 323 555 0199',
    email: 'info@africanartgallery.com',
    website: 'https://africanartgallery.com',
    images: [
      'https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    ],
    is_premium: false,
    status: 'active',
    views_count: 723,
    rating: 4.7,
    verified: true,
    created_at: '2024-07-15T09:00:00Z',
    updated_at: '2024-10-20T13:30:00Z',
  },
  {
    id: '7',
    owner_id: '7',
    owner_name: 'Chioma Nwosu',
    title: 'African Language School',
    description: 'Learn Swahili, Yoruba, Igbo, and other African languages. Online and in-person classes for all ages and skill levels.',
    category: ['Education', 'Professional Services'],
    address: '456 Learning Center',
    country: 'United States',
    city: 'Atlanta',
    phone: '+1 404 555 0234',
    email: 'info@africanlanguages.edu',
    website: 'https://africanlanguages.edu',
    images: [],
    is_premium: false,
    status: 'active',
    views_count: 612,
    rating: 4.8,
    verified: true,
    created_at: '2024-05-22T11:00:00Z',
    updated_at: '2024-10-19T15:45:00Z',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'e1',
    listing_id: '1',
    listing_title: 'Afro Fusion Restaurant',
    title: 'Afrobeat Night - Live Music & Dining',
    description: 'Join us for an unforgettable evening of live Afrobeat music, dancing, and delicious food. Featuring DJ Kofi and special guest performers.',
    start_datetime: '2024-11-15T19:00:00Z',
    end_datetime: '2024-11-15T23:00:00Z',
    location: 'Afro Fusion Restaurant, 123 High Street, London',
    banner_image: 'https://images.unsplash.com/photo-1594750852517-f37738fa2384?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    created_at: '2024-10-15T10:00:00Z',
  },
  {
    id: 'e2',
    listing_id: '2',
    listing_title: 'African Roots Fashion Boutique',
    title: 'African Fashion Week Pop-Up',
    description: 'Exclusive preview of our new collection inspired by traditional African patterns. Meet the designers, enjoy refreshments, and get 20% off all purchases.',
    start_datetime: '2024-11-20T14:00:00Z',
    end_datetime: '2024-11-20T18:00:00Z',
    location: 'African Roots Fashion Boutique, 45 Market Lane, New York',
    banner_image: 'https://images.unsplash.com/photo-1629299342303-3f3622666c41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    created_at: '2024-10-18T14:30:00Z',
  },
];

export const mockBlogs: BlogPost[] = [
  {
    id: 'b1',
    listing_id: '1',
    listing_title: 'Afro Fusion Restaurant',
    author_name: 'Amara Johnson',
    title: '5 Must-Try West African Dishes',
    content: '<p>West African cuisine is incredibly diverse and flavorful. Here are five dishes you absolutely must try...</p>',
    excerpt: 'Discover the rich flavors and cultural heritage behind these authentic West African dishes.',
    banner_image: 'https://images.unsplash.com/photo-1689155494424-d2337856fe3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    tags: ['Food', 'Culture', 'West Africa', 'Recipes'],
    published_at: '2024-10-20T09:00:00Z',
  },
  {
    id: 'b2',
    listing_id: '2',
    listing_title: 'African Roots Fashion Boutique',
    author_name: 'Kwame Asante',
    title: 'The Resurgence of African Print Fashion',
    content: '<p>African print fabrics are taking the global fashion world by storm. Learn about the history and modern interpretations...</p>',
    excerpt: 'How traditional African textiles are influencing contemporary fashion worldwide.',
    banner_image: 'https://images.unsplash.com/photo-1629299342303-3f3622666c41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    tags: ['Fashion', 'Culture', 'African Print', 'Style'],
    published_at: '2024-10-18T12:00:00Z',
  },
  {
    id: 'b3',
    listing_id: '3',
    listing_title: 'Zara\'s Beauty Lounge',
    author_name: 'Zara Okafor',
    title: 'Natural Hair Care Tips for Winter',
    content: '<p>As temperatures drop, natural hair requires special care. Here are my top tips for keeping your hair healthy and moisturized...</p>',
    excerpt: 'Essential winter hair care routine for natural and protective styles.',
    banner_image: 'https://images.unsplash.com/photo-1713845784497-fe3d7ed176d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080',
    tags: ['Beauty', 'Hair Care', 'Natural Hair', 'Winter Tips'],
    published_at: '2024-10-22T15:30:00Z',
  },
];

export const mockAnalytics: Analytics = {
  listing_id: '1',
  views: 2456,
  clicks: 456,
  contacts: 89,
  period: '30d',
  data: [
    { date: '2024-10-01', views: 65, clicks: 12, contacts: 2 },
    { date: '2024-10-02', views: 72, clicks: 15, contacts: 3 },
    { date: '2024-10-03', views: 58, clicks: 10, contacts: 1 },
    { date: '2024-10-04', views: 81, clicks: 18, contacts: 4 },
    { date: '2024-10-05', views: 95, clicks: 22, contacts: 5 },
    { date: '2024-10-06', views: 103, clicks: 25, contacts: 6 },
    { date: '2024-10-07', views: 88, clicks: 19, contacts: 3 },
    { date: '2024-10-08', views: 76, clicks: 16, contacts: 2 },
    { date: '2024-10-09', views: 69, clicks: 14, contacts: 3 },
    { date: '2024-10-10', views: 91, clicks: 21, contacts: 4 },
    { date: '2024-10-11', views: 84, clicks: 17, contacts: 3 },
    { date: '2024-10-12', views: 77, clicks: 15, contacts: 2 },
    { date: '2024-10-13', views: 98, clicks: 23, contacts: 5 },
    { date: '2024-10-14', views: 105, clicks: 26, contacts: 6 },
    { date: '2024-10-15', views: 112, clicks: 28, contacts: 7 },
  ],
};

// API Sample Payloads
export const API_SAMPLES = {
  // POST /listings - Create Listing
  createListing: {
    request: {
      title: 'My African Business',
      description: 'A comprehensive description of the business',
      category: ['Restaurant', 'Food & Grocery'],
      address: '123 Main Street',
      country: 'United Kingdom',
      city: 'London',
      phone: '+44 20 1234 5678',
      email: 'info@mybusiness.com',
      website: 'https://mybusiness.com',
      social_links: {
        facebook: 'mybusiness',
        instagram: 'mybusinessuk',
      },
      is_premium: true,
    },
    response: {
      success: true,
      listing: {
        id: '123',
        status: 'pending',
        // ... full listing object
      },
      payment_required: true,
      checkout_url: 'https://checkout.stripe.com/pay/cs_test_...',
    },
  },

  // GET /listings?q=restaurant&country=UK&premium=true
  searchListings: {
    request: {
      q: 'restaurant',
      category: ['Restaurant'],
      country: 'United Kingdom',
      premium: true,
      page: 1,
      perPage: 20,
    },
    response: {
      listings: mockListings.filter(l => l.is_premium),
      total: 3,
      page: 1,
      perPage: 20,
      totalPages: 1,
    },
  },

  // POST /payments/checkout
  createCheckout: {
    request: {
      plan: 'premium',
      listing_id: '123',
      billing_period: 'monthly',
    },
    response: {
      success: true,
      checkout_url: 'https://checkout.stripe.com/pay/cs_test_a1b2c3...',
      session_id: 'cs_test_a1b2c3d4e5f6g7h8i9j0',
    },
  },

  // POST /admin/approve-listing/:id
  approveListing: {
    request: {
      listing_id: '123',
      status: 'active',
    },
    response: {
      success: true,
      listing: {
        id: '123',
        status: 'active',
        // ... updated listing
      },
    },
  },
};
